### ISSUE TITLE
Bug: open in browser just has an iframe

### ISSUE THREAD

**Issue by F-loat** [7Flixs/vs_code_http_server_and_html_preview#2]
There are no html document and reset style when open in browser.

**Comment by 7Flixs** [comment]
Hey,

I'm not sure what you mean sorry, can you be more precise on what you mean?

Kind regards,

Shawn.

**Comment by F-loat** [comment]
Sorry for that. 

There are only an iframe in the source code. And `body` has default margin.

``` html
<!-- view-source:http://127.0.0.1:8080/ -->
<iframe src="index.html" id="shs_website" allowTransparency="false" frameborder="0"></iframe>
<script>
	// const websocket = new WebSocket("ws://127.0.0.1:8080");
	const websocket = new WebSocket("ws://" + document.location.host);

	websocket.onmessage = (event) => {
		if (event.data == "refresh") {
			const iframe = document.getElementById("shs_website")

			iframe.src = iframe.contentWindow.location.href
		}
	}
</script>
<style>
	body, html, iframe {
		height: 100%;
		width: 100%;
		margin: 0;
		padding: 0;
	}
</style>
```

Should the iframe wrap in a html document like this one below.

``` html
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Simple HTTP Server</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<style>
			body, html, iframe {
				height: calc(100% - 2px);
				width: 100%;
				margin: 0;
				padding: 0;
			}
		</style>
	</head>
	<body style="background-color: white;">
		<iframe src="http://{address}" allowTransparency="false" frameborder="0"></iframe>
	</body>
</html>
```

**Comment by 7Flixs** [comment]
Hey,

the "iframe"'s are there so i can refresh everything how i want it to, and show it in Visual Studio Code. Do you mean that the "body" style is having conflicts with your the rest of your website? The margin is there so the WebSite is right on the corner and not starting some where in the center.

Kind regards,

Shawn.

**Comment by F-loat** [comment]
![image](https://user-images.githubusercontent.com/16759376/41374181-0c4035ae-6f85-11e8-8e92-011fe469fc0b.png)

Maybe the picture is more accurate. I think body's margin should be reset.

``` css
html, body, iframe {
	height: 100%;
	width: 100%;
	margin: 0;
	padding: 0;
}
```

**Comment by 7Flixs** [comment]
Hey,

I've pushed a update `"1.0.3"`, here are the changes:

## [1.0.3]
- Removed unneeded code
- Added default settings css to the body for all Websites

There will still be a space on your website between the picture and the Browser border, but don't worry that is the default CSS margin, if you set your margin to 0, it'll dock right on the corners.
I hope this sovles your issue.

Kind regards,

Shawn.

**Comment by F-loat** [comment]
Thanks.
