### ISSUE TITLE
Feature Request: Retain scroll position when preview updates

### ISSUE THREAD

**Issue by dartrax** [7Flixs/vs_code_http_server_and_html_preview#3]
When the source html file changes, the preview gets updated. If the change is at the bottom of the page and you have scrolled down to preview the changes, every update of the preview resets scrolling position, so you have to scroll down over and over in a workflow where you are constantly editing and previewing your code.

So it would be nice if scrolling position gets saved and restored. I can imagine that this is not easily possible for extern browser preview, but may be it is possible for preview within VS Code.

**Comment by 7Flixs** [comment]
Hey,

I'm happy to announce version 2.0.0, I added the feature you requested and the scroll position will stay after the file got refreshed. For further information on what got released in 2.0.0, read here:

https://github.com/7Flixs/vs_code_http_server_and_html_preview/blob/master/CHANGELOG.md

Kind regards,

Shawn.

**Comment by dartrax** [comment]
Hi Shawn,
thank you for the quick fix!
I'm very happy with the extension.
